insert into languages (eng_name) values
("Čeština (CZ)"),
("Dansk (DA)"),
("Deutsch (DE)"),
("English (EN)"),
("Español (ES)"),
("Suomi (FI)"),
("Français (FR)"),
("Ελληνικά (GR)"),
("Magyar (HU)"),
("Bahasa Indonesia (ID)"),
("Italiano (IT)"),
("日本語 (JA)"),
("Bahasa Malay (MS)"),
("Nederlands (NL)"),
("Norsk (NO)"),
("Polski (PL)"),
("Português (PT)"),
("Română (RO)"),
("Русский (RU)"),
("Svenska (SV)"),
("ภาษาไทย (TH)"),
("Türkçe (TR)"),
("Українська (UK)"),
("Tiếng Việt (VI)"),
("中文 (ZH)"),
("繁體中文 (ZW)");